### ISSUE TITLE
Sorry, if this is not the place to report things

### ISSUE THREAD

**Issue by TheAinzSama** [NanoAdblocker/NanoDoc#1]
Hello, 

I am not sure if this is where you can report things, but I found a website that is able to dodge the adblocker. If you try to read a manga from kissmanga.com it does not display the manga, until you disable the adblocker.
http://kissmanga.com/Manga/Death-March-kara-Hajimaru-Isekai-Kyousoukyoku/Ch-045----A-Disturbing-Beginning?id=448005

**Comment by jspenguin2017** [comment]
This repository is for documentation only, I created a report here: https://github.com/NanoMeow/QuickReports/issues/124#issuecomment-427525694
